# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_group', to='otree.Session')),
            ],
            options={
                'db_table': 'bg_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('earnings', otree.db.models.FloatField(null=True)),
                ('max_buy', otree.db.models.IntegerField(null=True)),
                ('repetition', otree.db.models.IntegerField(null=True)),
                ('buy_1', otree.db.models.StringField(max_length=10000, null=True)),
                ('buy_1_price', otree.db.models.StringField(max_length=10000, null=True)),
                ('buy_2', otree.db.models.StringField(max_length=10000, null=True)),
                ('buy_2_price', otree.db.models.StringField(max_length=10000, null=True)),
                ('buy_3', otree.db.models.StringField(max_length=10000, null=True)),
                ('buy_3_price', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_1', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_2', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_3', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_4', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_5', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_6', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_7', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_8', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_9', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_10', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_11', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_12', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_13', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_14', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_15', otree.db.models.StringField(max_length=10000, null=True)),
                ('cq_16', otree.db.models.StringField(max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bg.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_player', to='otree.Session')),
            ],
            options={
                'db_table': 'bg_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bg_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'bg_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bg.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bg.Subsession'),
        ),
    ]
