# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-07 12:20
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0003_auto_20180907_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='buy_4',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='buy_4_price',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='buy_5',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='buy_5_price',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='buy_6',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='buy_6_price',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
