# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-07 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0004_auto_20180907_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='buy_4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='buy_4_price',
        ),
        migrations.RemoveField(
            model_name='player',
            name='buy_5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='buy_5_price',
        ),
        migrations.RemoveField(
            model_name='player',
            name='buy_6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='buy_6_price',
        ),
    ]
